package com.example.generics;

import java.lang.reflect.Array;
import java.lang.reflect.Method;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

/**
 * Section 3.3.4: Type Erasure, Bridge Methods, & Compile-Time Generic Warnings.
 * 
 * Demonstrates:
 * - Type Erasure at runtime (Class equality, erasure to Object/Bounds).
 * - Synthetic Bridge Methods generated by javac for generic inheritance.
 * - Raw Types & Heap Pollution hazards.
 * - @SuppressWarnings("unchecked") & @SafeVarargs usage.
 * - Generic Array Creation prohibition & reflection workaround via Array.newInstance().
 */
public class TypeErasureAndWarningsDemo {

    /**
     * Parent Generic Interface.
     */
    public interface NodeComparator<T> {
        int compare(T a, T b);
    }

    /**
     * Concrete implementation overriding compare(String, String).
     * Compiles into bytecode containing a synthetic bridge method compare(Object, Object)!
     */
    public static class StringNodeComparator implements NodeComparator<String> {
        @Override
        public int compare(String a, String b) {
            return a.compareTo(b);
        }
    }

    /**
     * Generic Array Container demonstrating why 'new T[size]' is invalid
     * and how to implement safe generic arrays via Array.newInstance().
     */
    public static class GenericArrayBuffer<T> {
        private final T[] array;

        @SuppressWarnings("unchecked")
        public GenericArrayBuffer(Class<T> clazz, int capacity) {
            // T[] arr = new T[capacity]; // COMPILE ERROR! Cannot create a generic array of T directly
            // Safe Workaround: Use Array.newInstance with Class token
            this.array = (T[]) Array.newInstance(clazz, capacity);
        }

        public void set(int index, T item) {
            array[index] = item;
        }

        public T get(int index) {
            return array[index];
        }

        public T[] getArray() {
            return array;
        }
    }

    /**
     * Demonstrates Varargs with Non-Reifiable Generic Types.
     * Requires @SafeVarargs when method is final/static/private to suppress potential heap pollution warning.
     */
    @SafeVarargs
    public static <T> List<T> combineLists(List<T>... lists) {
        List<T> combined = new ArrayList<>();
        for (List<T> list : lists) {
            combined.addAll(list);
        }
        return combined;
    }

    /**
     * Demonstrates Heap Pollution via Raw Types.
     */
    @SuppressWarnings({"rawtypes", "unchecked"})
    public static void demonstrateHeapPollution() {
        List<String> stringList = new ArrayList<>();
        List rawList = stringList; // Raw type reference pointing to generic list
        
        rawList.add(42); // Adding Integer into List<String> via Raw type! (Heap Pollution)

        System.out.println("Raw type bypassed compile-time check! Content: " + stringList);
        try {
            // Compiler inserts implicit (String) cast here due to erasure of List<String>
            String str = stringList.get(0);
            System.out.println("Retrieved string: " + str);
        } catch (ClassCastException e) {
            System.err.println("🔥 HEAP POLLUTION BURST! ClassCastException: " + e.getMessage());
        }
    }

    public static void runDemo() {
        System.out.println("\n------------------------------------------------------------------------");
        System.out.println("📌 3.3.4 TYPE ERASURE, BRIDGE METHODS & GENERIC WARNINGS");
        System.out.println("------------------------------------------------------------------------");

        // 1. Type Erasure Runtime Proof
        System.out.println("\n--- 1. Type Erasure Runtime Class Proof ---");
        List<String> stringList = new ArrayList<>();
        List<Integer> intList = new ArrayList<>();

        System.out.println("stringList.getClass() : " + stringList.getClass().getName());
        System.out.println("intList.getClass()    : " + intList.getClass().getName());
        boolean sameClass = stringList.getClass() == intList.getClass();
        System.out.println("Are classes equal?    : " + sameClass + " (Generic types erased to java.util.ArrayList)");

        // 2. Synthetic Bridge Methods Inspection
        System.out.println("\n--- 2. Synthetic Bridge Methods Reflection Inspection ---");
        Class<?> clazz = StringNodeComparator.class;
        Method[] methods = clazz.getDeclaredMethods();

        System.out.println("Declared methods in StringNodeComparator:");
        for (Method m : methods) {
            System.out.printf("  - %-30s | isBridge: %-5b | isSynthetic: %b\n",
                    m.getName() + Arrays.toString(m.getParameterTypes()),
                    m.isBridge(),
                    m.isSynthetic());
        }
        System.out.println("💡 Bridge Method Explanation: javac generates compare(Object, Object) bridge method");
        System.out.println("   to override NodeComparator.compare(Object) and delegate to compare(String, String).");

        // 3. Heap Pollution Hazard
        System.out.println("\n--- 3. Heap Pollution Hazard & Raw Types ---");
        demonstrateHeapPollution();

        // 4. Safe Generic Array Creation via Reflection
        System.out.println("\n--- 4. Safe Generic Array Buffer (Array.newInstance) ---");
        GenericArrayBuffer<String> stringBuffer = new GenericArrayBuffer<>(String.class, 3);
        stringBuffer.set(0, "cluster-node-a");
        stringBuffer.set(1, "cluster-node-b");
        stringBuffer.set(2, "cluster-node-c");

        System.out.println("Generic Array Buffer element 1: " + stringBuffer.get(1));
        System.out.println("Underlying Array Type          : " + stringBuffer.getArray().getClass().getTypeName());

        // 5. @SafeVarargs Demonstration
        System.out.println("\n--- 5. @SafeVarargs Generic Varargs Combination ---");
        List<String> l1 = List.of("prod-db-1");
        List<String> l2 = List.of("prod-db-2", "prod-db-3");
        List<String> combined = combineLists(l1, l2);
        System.out.println("Combined Varargs Lists        : " + combined);

        System.out.println("\n💡 SRE Safety Rules:");
        System.out.println("   1. NEVER use Raw Types in production code; they disable type safety and cause delayed ClassCastException at runtime.");
        System.out.println("   2. Always annotate varargs methods taking generic types with @SafeVarargs when type safety is guaranteed.");
        System.out.println("   3. Generic types exist ONLY at compile time; runtime reflection sees raw erased types.");
    }
}
